# Generated by Django 4.2.4 on 2023-08-20 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Покупатель')),
                ('is_actual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Покупатели',
                'verbose_name_plural': 'Покупатели',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='Драгоценный камень')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Количество товара не может быть меньше 1!')], verbose_name='Количество товара')),
                ('total', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Сумма сделки не может быть меньше 1!')], verbose_name='Сумма сделки')),
                ('deal_date', models.DateTimeField(verbose_name='Дата сделки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'db_table': 'deals',
            },
        ),
    ]
